//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillOfMaterial
    {
        public int BillOfMaterialID { get; set; }
        public Nullable<int> MaterialProduccionID { get; set; }
        public Nullable<int> TipoOperacionID { get; set; }
        public Nullable<int> TipoMovimientoSAPID { get; set; }
        public Nullable<decimal> FactorConsumo { get; set; }
        public Nullable<int> EquipoID { get; set; }
        public Nullable<bool> ConsumoSeco { get; set; }
        public Nullable<bool> ConsumoHumedo { get; set; }
        public Nullable<System.DateTime> FechaBOM { get; set; }
        public Nullable<int> MaterialConsumoID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> ProduccionSeca { get; set; }
        public Nullable<bool> ProduccionHumeda { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual TipoOperacion TipoOperacion { get; set; }
        public virtual Material Material { get; set; }
        public virtual Material Material1 { get; set; }
        public virtual TipoMovimientoSAP TipoMovimientoSAP { get; set; }
    }
}
