//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataOperacion
    {
        public int DataOperacionID { get; set; }
        public Nullable<int> EquipoID { get; set; }
        public Nullable<int> TipoOperacionID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<decimal> CantidadObtenida { get; set; }
        public Nullable<decimal> CantidadReal { get; set; }
        public Nullable<int> UnidadMedidaID { get; set; }
        public Nullable<int> TipoMovimientoSAPID { get; set; }
        public Nullable<System.DateTime> FechaReporte { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual Material Material1 { get; set; }
        public virtual TipoMovimientoSAP TipoMovimientoSAP { get; set; }
        public virtual TipoOperacion TipoOperacion { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
