//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.DataOperacion = new HashSet<DataOperacion>();
            this.Paros = new HashSet<Paros>();
            this.SubEquipo = new HashSet<SubEquipo>();
            this.TagEquipo = new HashSet<TagEquipo>();
        }
    
        public int EquipoID { get; set; }
        public string Descripcion { get; set; }
        public string CondigoDetalle { get; set; }
        public string CondigoSAP { get; set; }
        public Nullable<int> ProcesoID { get; set; }
        public Nullable<int> PlantaID { get; set; }
        public Nullable<int> UnidadOperativaID { get; set; }
        public Nullable<int> PaisID { get; set; }
        public Nullable<bool> BuscarParo { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataOperacion> DataOperacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paros> Paros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubEquipo> SubEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagEquipo> TagEquipo { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Planta Planta { get; set; }
        public virtual Proceso Proceso { get; set; }
        public virtual UnidadOperativa UnidadOperativa { get; set; }
    }
}
