//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.BillOfMaterial = new HashSet<BillOfMaterial>();
            this.DataOperacion = new HashSet<DataOperacion>();
            this.DataOperacion1 = new HashSet<DataOperacion>();
        }
    
        public int MaterialID { get; set; }
        public string Descripcion { get; set; }
        public string CodSAPNuevo { get; set; }
        public string CodOldSAP { get; set; }
        public Nullable<bool> Producido { get; set; }
        public Nullable<int> ClasificacionMaterialID { get; set; }
        public Nullable<bool> Alterno { get; set; }
        public Nullable<bool> AfectaInventario { get; set; }
        public string IDStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfMaterial> BillOfMaterial { get; set; }
        public virtual ClasificacionMaterial ClasificacionMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataOperacion> DataOperacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataOperacion> DataOperacion1 { get; set; }
    }
}
