//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.BillOfMaterial = new HashSet<BillOfMaterial>();
            this.BillOfMaterial1 = new HashSet<BillOfMaterial>();
            this.DataOperacion = new HashSet<DataOperacion>();
            this.DataOperacion1 = new HashSet<DataOperacion>();
            this.TagEquipo = new HashSet<TagEquipo>();
        }
    
        public int MaterialID { get; set; }
        public string Descripcion { get; set; }
        public string CodSAPNuevo { get; set; }
        public string CodOldSAP { get; set; }
        public Nullable<bool> Producido { get; set; }
        public Nullable<int> ClasificacionMaterialID { get; set; }
        public Nullable<bool> Alterno { get; set; }
        public Nullable<bool> AfectaInventario { get; set; }
        public string IDStock { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> PlantaID { get; set; }
        public Nullable<int> UnidadMedidaID { get; set; }
        public Nullable<bool> Consumido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfMaterial> BillOfMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfMaterial> BillOfMaterial1 { get; set; }
        public virtual ClasificacionMaterial ClasificacionMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataOperacion> DataOperacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataOperacion> DataOperacion1 { get; set; }
        public virtual Planta Planta { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagEquipo> TagEquipo { get; set; }
    }
}
