//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paros()
        {
            this.CierreStatus = new HashSet<CierreStatus>();
        }
    
        public int ParosID { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaEvento { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> EquipoID { get; set; }
        public Nullable<int> SubEquipoID { get; set; }
        public Nullable<int> ComponenteEquipoID { get; set; }
        public Nullable<int> ClasificacionID { get; set; }
        public Nullable<int> TipoFallaID { get; set; }
        public Nullable<bool> StatusValidate { get; set; }
        public Nullable<bool> StatusDelete { get; set; }
        public Nullable<int> TipoEventoID { get; set; }
        public Nullable<int> UsuarioCreadorID { get; set; }
        public Nullable<int> ParoRelacionadoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CierreStatus> CierreStatus { get; set; }
        public virtual Clasificacion Clasificacion { get; set; }
        public virtual ComponenteEquipo ComponenteEquipo { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual SubEquipo SubEquipo { get; set; }
        public virtual TipoEvento TipoEvento { get; set; }
        public virtual TipoFalla TipoFalla { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
