//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagEquipo
    {
        public int TagEquipoID { get; set; }
        public string Descripcion { get; set; }
        public string TagName { get; set; }
        public string TagCode { get; set; }
        public Nullable<int> EquipoID { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
