//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoFalla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoFalla()
        {
            this.Paros = new HashSet<Paros>();
        }
    
        public int TipoFallaID { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ClasificacionID { get; set; }
        public Nullable<int> ComponenteEquipoID { get; set; }
    
        public virtual Clasificacion Clasificacion { get; set; }
        public virtual ComponenteEquipo ComponenteEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paros> Paros { get; set; }
    }
}
